### ISSUE TITLE
Nuxt error when using a blueprint.

### ISSUE THREAD

**Issue by chriscab83** [nuxt-alt/vuetify#1]
When adding a `blueprint` vuetify option, Nuxt goes into an infinite loop and hits a call stack error.

To replicate:

`nuxt.config.ts`
```javascript
import { defineNuxtConfig } from "nuxt/config";
import { md1 } from "vuetify/blueprints";
import MyModule from "..";

export default defineNuxtConfig({
  modules: [MyModule],
  vuetify: {
    vuetifyOptions: {
      blueprint: md1,
    },
  },
});
```

The error:
<img width="456" alt="Screenshot 2022-12-13 at 11 32 53 AM" src="https://user-images.githubusercontent.com/4398550/207390235-b15238dc-7f4d-4f75-adde-ddad6589cf00.png">

**Comment by Teranode** [comment]
- Update to version 1.0.8.
- remove `import { md1 } from "vuetify/blueprints";`
- Replace `blueprint: md1` with `blueprint: 'md1'`

it will get the blueprint on the plugin side, so you just need to specify it in string form
