### ISSUE TITLE
Incompatible with nuxt-vitest

### ISSUE THREAD

**Issue by scscgit** [nuxt-alt/vuetify#9]
* Install dependencies:
`"nuxt": "^3.4.3",`
`"@nuxt-alt/vuetify": "^1.1.1",`
`"`[nuxt-vitest](https://github.com/danielroe/nuxt-vitest)`": "^0.6.10",`

* Add both modules to `nuxt.config.ts` (any order):
```ts
export default defineNuxtConfig({
  modules: ['nuxt-vitest','@nuxt-alt/vuetify']
})
```

* Add file `vitest.config.mjs` to the project root directory with the following content:
```js
import { defineVitestConfig } from 'nuxt-vitest'

export default defineVitestConfig({})
```

* (Optional) add any test

* Run `npm run test` with script in `package.json`:
```
"scripts": {
    "test": "vitest",
  },
```
Following error occurs:
```cmd
> vitest
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Error: Vuetify plugin must be loaded after the vue plugin
    at configResolved (~\node_modules\vite-plugin-vuetify\dist\importPlugin.js:19:23)
```
(as the `config.plugins.findIndex(plugin => plugin.name === 'vite:vue')` unexpectedly matches the plugin.)

**Comment by Teranode** [comment]
PRs are welcomed.

**Comment by scscgit** [comment]
This issue has meanwhile been fixed in [nuxt-vitest](https://github.com/danielroe/nuxt-vitest) version `0.6.11` (mentioned in https://github.com/danielroe/nuxt-vitest/issues/151#issuecomment-1535280171)
